name: HorseRacingPlus
main: com.comze_instancelabs.horseracingplus.Main
version: 1.4.1
author: [instancelabs,mepeisen]
permissions:
  horseracing.createrace:
    description: Gives access to create a race.
  horseracing.setlobby:
    description: Gives access to set a lobby.
  horseracing.setspawn:
    description: Gives access to set a spawn.
  horseracing.removerace:
    description: Gives access to remove a race.
  horseracing.setfinish:
    description: Gives access to set the finish line.
  horseracing.sign:
    description: Gives access to create a race sign.
commands:
   horseracing:
      description: Main command
      usage: /horseracing
   hr:
      description: Main command
      usage: /hr